swagger: "2.0"
info:
  title: Duolingo Deck Converter 
  description: API for converting duolingos deck.csv into something that's not steaming garbage. 
  version: 1.0.0
paths:
  /duolingo/deck/conversion:
    post:
      summary: Takes the deck csv file and converts to json. 
      consumes:
         - multipart/form-data
      parameters:
        - in: formData
          name: dulingoDeckCsvFile 
          type: file
          description: The file to upload.      
      produces:
          - application/json
      responses:
        200:
          description: returns a list of subway lines and Ids 